Unity-Technologies/com.autodesk.fbx

- Source/fbxmesh.i
- tests/RuntimeTests/Editor/UnitTests/FbxMeshTest.cs
This PR exposes the function FbxMesh::GetPolygonVertexNormal()
I used a typemap for the out parameter that returns the normal. Without doing that, swig would generate a SWIGTYPE_p_FbxVector4 instead of using the dedicated optimized struct. Not sure if that's how it's intended to be used.
For the unit test I currently use FloatEqualityComparers to check if the normals that are read back, are approximately equal to the ones that were set. This is a bit verbose as you can see.
Some ideas for improvement:
- Unity's Vector3 class overrides the == operator so that it does approximate comparison. The same might make sense to do with FbxVector4s (and of course FbxVector2s) as well.
- One could write a dedicated IEqualityComparer for FbxVector structs that does approximate comparison [like the …
> add FbxMesh binding for GetPolygonVertexNormal

- .yamato/yamato.yml
temporary fix, ideally we would have our own bokken image with everything already installed: https://imgspc.atlassian.net/browse/UT-3796
> UT-3798 fix mac build failing when installing mono

- proto.com.autodesk.fbx/Documentation~/api_index.md
- proto.com.autodesk.fbx/Documentation~/index.md
- proto.com.autodesk.fbx/package.json.in
Reviewed and updated the package documentation according to:
- FBX-9 - Verify that 4.0.0-pre.1 doc follows templates
- FBX-10 - Verify that 4.0.0-pre.1 doc makes sense
- FBX-11 - Verify that 4.0.0-pre.1 doc Documentation follows a writing style guide
- FBX-12 - Verify that 4.0.0-pre.1 doc package summary is edited
Note: Scripting API section can now have a landing page with custom content, that's why I've split the index in 2 files (one for manual, the other for API).
Tested: successfully built using PackMan docs tool.
> Doc release 4.0 review

- proto.com.autodesk.fbx/Documentation~/config.json
- binding API documentation was not generated because of #if UNITY_EDITOR || FBXSDK_RUNTIME preprocessor directives.
> FBX-27 add defines to use when generating documentation

- .yamato/yamato.yml
- tests/RuntimeTests/Editor/BuildTests/BuildTest.cs
Setting scripting backend to il2cpp will install il2cpp, but not change the project settings (unless platform is standalone).
Therefore, always use il2cpp (except ubuntu 2018.4 which does not have it), and modify the backend for the test that needs it to be il2cpp.
> Ut 3782/fix tests failing on il2cpp

- README.md
I have modified the commands listed in the README.
The files `build.sh` and `build.cmd` are mentioned in the README, but they don't exist, instead there is a file `build.py`.
I ran `python build.py` to see if it worked, and it did, so I fixed the README.
> Fix build.cmd to build.py

- tests/RuntimeTests/Editor/BuildTests/BuildTest.cs
These fail on the final release CI because not all backends are installed,
and we're testing them all no matter what.
> FBX-103: disable build tests

- .yamato/yamato.yml
- tests/RuntimeTests/Editor/BuildTests/FbxBuildTest.asmdef
- tests/RuntimeTests/Editor/LinuxTests.meta
- tests/RuntimeTests/Editor/LinuxTests/LinuxTest.asmdef
- tests/RuntimeTests/Editor/LinuxTests/LinuxTest.asmdef.meta
- tests/RuntimeTests/Editor/LinuxTests/LinuxTest.cs
- tests/RuntimeTests/Editor/LinuxTests/LinuxTest.cs.meta
- tests/RuntimeTests/Editor/PlayModeTests/PlayModeTests.asmdef
- tests/RuntimeTests/Editor/UnitTests/FbxUnitTests.asmdef
- tests/RuntimeTests/Editor/UseCaseTests/FbxUseCaseTests.asmdef
- tests/RuntimeTests/Runtime/BuildTestsAssets/FbxBuildTestAssets.asmdef
This is for the 4.0.1 release with Unity 2021.1 ; we should re-enable them for
2021.2 when we have time to deal with the libstdc++ issue.
> FBX-100: disable tests on linux

- Source/fbxproperty.i
- tests/RuntimeTests/Editor/UnitTests/FbxPropertyTest.cs
The following function override now gets generated in FbxProperty.cs:
```
public bool Set(float pValue) {
bool ret = NativeMethods.FbxProperty_Set__SWIG_2(swigCPtr, pValue);
if (NativeMethods.SWIGPendingException.Pending) throw NativeMethods.SWIGPendingException.Retrieve();
return ret;
}
```
Added automated test.
Built and tested on Unity 2021.1
> FBX-46: Enable setting a string in a custom property

- proto.com.autodesk.fbx/ValidationExceptions.json
To prepare 4.2.0 release
The need for this validation will disapear in 5.X (FBX-293)
> Package: update the validation exception (FBX-316)

- proto.com.autodesk.fbx/Editor/Scripts/PostProcessAddToBuild.cs
**To reproduce:**
- A minimal project using the FBX SDK C# bindings at runtime (including having FBXSDK_RUNTIME in the Scripting Define Symbols)
- Build the project for Windows Standalone. This does not display any error
- Build the project a second time, this time overwrite the existing player.
**Expected Behavior:**
The build completes without error.
**Actual Behavior:**
The following exception is thrown:
`IOException: The file 'E:\Unity\FBXTest\Builds\Test\FBXTest_Data\Plugins\UnityFbxSdkNative.dll' already exists.
System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) (at <6073cf49ed704e958b8a66d540dea948>:0)
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at …
> Fix IOException during build when overwriting an existing build.

- .yamato/yamato.yml
Package `com.unity.testtools.codecoverage@1.1.1` has compatibility issues with `com.unity.test-framework@1.3.x` versions.
The problem has been fixed in `com.unity.testtools.codecoverage@1.2.2`.
Before a new version of UTR which includes `com.unity.testtools.codecoverage@1.2.2` is released, we need to explicitly set codecoverage package version in upm-ci command.
> Explicitly set codecoverage package to 1.2.2 to fix code coverage failures

- .yamato/yamato.yml
Package com.unity.testtools.codecoverage@1.1.1 has compatibility issues with com.unity.test-framework@1.3.x versions.  
The problem has been fixed in com.unity.testtools.codecoverage@1.2.2.  
Before a new version of UTR which includes com.unity.testtools.codecoverage@1.2.2 is released, we need to explicitly set codecoverage package version in upm-ci command.
> Explicitly set codecoverage package version to 1.2.2 to fix code coverage failures for release 4.1 branch

- .yamato/yamato.yml
Explicitly set codecoverage package version to 1.2.2 to fix code coverage failures for release 4.2 branch
> Explicitly set codecoverage package version to 1.2.2 to fix code coverage failures for release 4.2 branch

- .yamato/yamato.yml
Explicitly set codecoverage package version to 1.2.2 to fix code coverage failures for release 5.0 branch
> Explicitly set codecoverage package version to 1.2.2 to fix code coverage failures for release 5.0 branch

- .yamato/global.metafile
- .yamato/yamato.yml
In #372 , some master specific changes (the ones in .yamato folder) were merged into 4.2 branch unexpectedly, especially the ones about editor versions.
This PR does followings:
- Put back versions 2018.4 and 2019.4
- Use new package-ci images (v4 ones) for package test, old mac and ubuntu images are still needed for build jobs
- Add a `publish_dry_run` job so we can test publishing before real publishing
- Some other minor changes to CI
**JIRA ticket#**
[FBX-439](https://jira.unity3d.com/browse/FBX-439) Fix editor versions in CI for release/4.1 and release/4.2 branches
> FBX-439 Fix editor versions in CI for release/4.2 branch

- .yamato/global.metafile
- .yamato/yamato.yml
In #371, some master specific changes (the ones in .yamato folder) were merged into 4.1 branch unexpectedly, especially the ones about editor versions.
This PR does followings:
- Put back versions 2018.4 and 2019.4
- Use new package-ci images (v4 ones) for package test, old mac and ubuntu images are still needed for build jobs
- Add a publish_dry_run job so we can test publishing before real publishing
- Some other minor changes to CI
- 
JIRA ticket#
[FBX-439](https://jira.unity3d.com/browse/FBX-439) Fix editor versions in CI for release/4.1 and release/4.2 branches
> FBX-439 Fix editor versions in CI for release/4.1 branch

- .yamato/global.metafile
- .yamato/yamato.yml
Update bokken images to new ones in CI
**JIRA tickets:**
[FBX-447](https://jira.unity3d.com/browse/FBX-447)
Investigate build failures on new package-ci images: macos-12:v4 and ubuntu18.04:v4 for com.autodesk.fbx package
[FBX-453](https://jira.unity3d.com/browse/FBX-453)
CI: Investigate "Build on mac" job failure
**Changes of this PR:**
- Update bokken images to new ones (v4 ones)
- Install cmake on `macos-12:v4` and `ubuntu-18.04:v4` 
- Remove mono install command on mac because mono is preinstalled on `macos-12:v4`
- Install `libxml2-dev` on `ubuntu-18.04:v4` 
- Do some cleanup and refactoring to global.metafile
- Add a publish dry-run job
> FBX-447: Update bokken images and refactor CI

- .yamato/global.metafile
- .yamato/yamato.yml
Backport #385 to release/5.0 branch.
**JIRA tickets:**
[FBX-447](https://jira.unity3d.com/browse/FBX-447)
Investigate build failures on new package-ci images: macos-12:v4 and ubuntu18.04:v4 for com.autodesk.fbx package
[FBX-453](https://jira.unity3d.com/browse/FBX-453)
CI: Investigate "Build on mac" job failure
> FBX-447: Update bokken images and refactor CI (Backport #385 to release/5.0)

- .yamato/global.metafile
- .yamato/yamato.yml
Backport https://github.com/Unity-Technologies/com.autodesk.fbx/pull/385 to release/4.1 branch.
**JIRA tickets:**
[FBX-447](https://jira.unity3d.com/browse/FBX-447)
Investigate build failures on new package-ci images: macos-12:v4 and ubuntu18.04:v4 for com.autodesk.fbx package
[FBX-453](https://jira.unity3d.com/browse/FBX-453)
CI: Investigate "Build on mac" job failure
> FBX-447: Update bokken images and refactor CI (Backport #385 to release/4.1)

- .yamato/global.metafile
- .yamato/yamato.yml
Backport https://github.com/Unity-Technologies/com.autodesk.fbx/pull/385 to release/4.2 branch.
**JIRA tickets:**
[FBX-447](https://jira.unity3d.com/browse/FBX-447)
Investigate build failures on new package-ci images: macos-12:v4 and ubuntu18.04:v4 for com.autodesk.fbx package
[FBX-453](https://jira.unity3d.com/browse/FBX-453)
CI: Investigate "Build on mac" job failure
> FBX-447: Update bokken images and refactor CI (Backport #385 to release/4.2) 

- .yamato/yamato.yml
Previously `build_win` job needs a Win VM with GPU to run. GPU resources are limited and the distribution time for GPU is very long.
Tried with `win10:v4` image today and found GPU is not needed any more for build_win job which will save a lot of time for CI pipeline.
> Nojira: Remove GPU for build_win job

- .yamato/yamato.yml
GPU is not needed for `build_win` job anymore
> Nojira: GPU is not needed for build_win anymore (release/5.0)

- .yamato/yamato.yml
Remove GPU from build_win job, it is not needed now.
> Nojira: Remove GPU from build_win job (release/4.1)

- .yamato/yamato.yml
Remove GPU from build_win job, it is not needed now.
> Nojira: Remove GPU from build_win job (release/4.2)

- build_linux.sh
Add 'set -e' so that build script on Linux will not fail silently. A little improvement to CI.
> Nojira: Add 'set -e' so that build script on Linux will not fail silently

- .yamato/global.metafile
- build_linux.sh
Fix com.autodesk build failure on Ubuntu 20
**JIRA ticket:**
[FBX-465](https://jira.unity3d.com/browse/FBX-465) CI: Fix com.autodesk build failure on Ubuntu 20
> FBX-465 CI: Fix com.autodesk build failure on Ubuntu 20

- .yamato/global.metafile
- build_linux.sh
[Build on Ubuntu](https://unity-ci.cds.internal.unity3d.com/project/178/branch/master/jobDefinition/.yamato%2Fpack-autodesk-fbx.yml%23build_ubuntu) also began to fail on 6th July and [Build on Mac](https://unity-ci.cds.internal.unity3d.com/project/178/branch/master/jobDefinition/.yamato%2Fpack-autodesk-fbx.yml%23build_mac) job began to fail on around 1st July.
Without this PR, I see a following build error on Mac:
```
/Users/bokken/build/output/Unity-Technologies/com.autodesk.fbx/build/deps/fbxsdk-mac-x64/include/fbxsdk/core/arch/fbxstdcompliant.h:52:96: error: 'vsprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead. …
```
> FBX-479 CI: Fix build job failures on Mac and Ubuntu

- .yamato/global.metafile
- .yamato/yamato.yml
Fix build job failures on Ubuntu and Mac for release/4.1 branch. This is a backport PR.
JIRA ticket:
[FBX-479](https://jira.unity3d.com/browse/FBX-479) CI: Fix build job failures on Mac and Ubuntu
> FBX-479 CI: Fix build errors on Ubuntu and Mac for release/4.1 branch

- .yamato/global.metafile
- .yamato/yamato.yml
Fix build job failures on Ubuntu and Mac for release/4.2 branch. This is a backport PR.
**JIRA ticket:**
[FBX-479](https://jira.unity3d.com/browse/FBX-479) CI: Fix build job failures on Mac and Ubuntu
> FBX-479 CI: Fix build job failures on Ubuntu and Mac for release/4.2 branch

- .yamato/global.metafile
- .yamato/yamato.yml
Fix build job failures on Ubuntu and Mac (release/5.0). This is a backport PR into release/5.0 branch.
**JIRA ticket: **
[FBX-479](https://jira.unity3d.com/browse/FBX-479) CI: Fix build job failures on Mac and Ubuntu
> FBX-479 CI: Fix build job failures on Ubuntu and Mac (release/5.0)

- .yamato/yamato.yml
- tests/RuntimeTests/Editor/BuildTests/Autodesk.Fbx.BuildTest.asmdef
- tests/RuntimeTests/Editor/PlayModeTests/Autodesk.Fbx.PlayModeTests.asmdef
- tests/RuntimeTests/Editor/UnitTests/Autodesk.Fbx.UnitTests.asmdef
- tests/RuntimeTests/Editor/UseCaseTests/Autodesk.Fbx.UseCaseTests.asmdef
- tests/RuntimeTests/Runtime/BuildTestsAssets/Autodesk.Fbx.BuildTestAssets.asmdef
The goal is to make the tests run again on our CI again.
Issues remain on Ubuntu18 (so with APV/QV), but can be workaround using the package exemption mechanism.
- Re-enabling Linux tests
- See corresponding [PR](https://github.com/Unity-Technologies/com.unity.formats.fbx/pull/699) for the exporter
> Re-enable Ubuntu tests (FBX-468)

- .yamato/global.metafile
- .yamato/yamato.yml
Run FBX SDK tests on Silicon Mac VM and add missing editors to CI.
**List of changes:**
- Add a `mac_arm64_platform` to CI which will run macOS 13 on Apple Silicon VM
- Add Editors `2022.3` and `2023.2` to CI for better coverage
- Clean up some outdated codes in CI which still refer to `2018.4`
- Remove promotion test from PR trigger. First promotion test shouldn't be in PR trigger, second it fails most of the time complaining the current package version already exists in package registry.
**JIRA ticket:**
[FBX-132](https://jira.unity3d.com/browse/FBX-132) Run automated tests on Apple Silicon machine
> CI: FBX-132 Run automated tests on Apple Silicon machine and add missing Editors

- .yamato/global.metafile
- .yamato/yamato.yml
- Add test jobs on ARM64 Win.
- Also removed 2023.1 from CI and change image flavor from `b1.medium` to `b1.large` which is the recommended one.
JIRA ticket:
[FBX-519](https://jira.unity3d.com/browse/FBX-519) CI: Add package test jobs for ARM64 Windows
> CI: Add package test jobs on ARM64 Windows for FBX SDK

- .yamato/global.metafile
- .yamato/yamato.yml
- build.py
- build_win.cmd
Add a build job for ARM64 Windows.
On ARM64 Win bokken VM, it is x64 version Python 3 installed. Because of that, `platform.machine()` returns `AMD64` even it is a `ARM64` machine. This is a similar issue to x64 version CMake on ARM64 Win: CMAKE_SYSTEM_PROCESSOR returns AMD64.
Because of that, I decide to:
- Add a new flag `--target` to build.py script
- In `build.cmd`, pass  `--target %PROCESSOR_ARCHITECTURE%` which is retrieved from the system directly to `build.py`. By doing this, we can work around the issue above. 
***JIRA ticket:*
[FBX-517](https://jira.unity3d.com/browse/FBX-517) Create Yamato job to build library on Win ARM64
> Add build jobs on Arm64 Win

- .yamato/global.metafile
Remove 2022.2, 2023.1, trunk from CI of release/5.0 branch.
Add 2022.3 to CI of release/5.0 branch.
**JIRA ticket:**
[FBX-494](https://jira.unity3d.com/browse/FBX-494) CI: Editor cleanup in CI of both FBX SDK and FBX Exporter for release/5.0 branch
> CI: Remove 2022.2, 2023.1, trunk and add 2022.3 in CI of release 5.0 branch
